---
- name: RUN COMMAND AND PRINT TO TERMINAL WINDOW
  hosts: ios
  gather_facts: false
  
  tasks:

    - name: AAA
      ios_config:
        lines:
          - aaa authentication login default group ISE local none
          - aaa authentication enable default group ISE enable none

