---
- name: RUN COMMAND AND PRINT TO TERMINAL WINDOW
  hosts: ios
  gather_facts: false
  
  tasks:

    - name: AAA Server 1
      ios_config:
        lines:
          - address ipv4 192.168.99.250
          - key asdf
        parents: tacacs server ISE01

    - name: AAA Server 2
      ios_config:
        lines:
          - address ipv4 192.168.33.250
          - key asdf
        parents: tacacs server ISE02



    - name: AAA Server Group
      ios_config:
        lines:
          - server name ISE01
          - server name ISE02
        parents: aaa group server tacacs+ ISE



    - name: AAA
      ios_config:
        lines:
          - username local privilege 15 password 0 asdf
          - username helpdesk password 0 asdf
          - aaa new-model
          - aaa authentication login default group ISE local none
          - aaa authentication enable default group ISE enable none
          - aaa authorization config-commands
          - aaa authorization exec default group ISE local none
          - aaa authorization commands 0 default group ISE local none
          - aaa authorization commands 1 default group ISE local none
          - aaa authorization commands 7 default group ISE local none
          - aaa authorization commands 15 default group ISE local none
          - aaa accounting exec default start-stop group ISE
          - aaa accounting commands 7 default start-stop group ISE
          - aaa accounting commands 15 default start-stop group ISE






