---
- name: RUN COMMAND AND PRINT TO TERMINAL WINDOW
  hosts: ios
  gather_facts: false
  
  tasks:
         
          
    - name: AAA Server 1
      ios_config:
        lines:
          - address ipv4 192.168.99.250
          - key asdf
        parents: tacacs server ISE01


    


