---
- name: RUN COMMAND AND PRINT TO TERMINAL WINDOW
  hosts: ios
  gather_facts: false
  
  tasks:
    - name: OSPF Process
      ios_config:
        lines:
          - tacacs server ISE03_test

    - name: OSPF Process - Router ID
      ios_config:
        lines: 
          - address ipv4 92.68.1.34
          - key asdf
        parents: tacacs server ISE01_test

