---
- name: RUN COMMAND AND PRINT TO TERMINAL WINDOW
  hosts: ios
  gather_facts: false
  
  tasks:
    - name: OSPF Process
      ios_config:
        lines:
          - tacacs server ISE01

    - name: OSPF Process - Router ID
      ios_config:
        lines: 
          - address ipv4 192.168.99.250
          - key asdf
        parents: tacacs server ISE01

