---
- name: RUN COMMAND AND PRINT TO TERMINAL WINDOW
  hosts: ios
  gather_facts: false


  tasks:
 
   - name: show run
     ios_command:
       commands:
       - show run
       - show ip route
       - show ip eigrp neighbors
       - show version
     register: output

   - name: save output to local directory
     debug: var=output.stdout
