---
- name: RUN COMMAND AND PRINT TO TERMINAL WINDOW
  hosts: ios
  gather_facts: false
  
  tasks:
    - name: CAPTURE SHOW IP INTERFACE
      ios_command:
        commands:
          - show ip interface brief
      register: output

    - name: DISPLAY THE OUTPUT
      debug: var=output.stdout
