---
- name: asdf
  hosts: ios
  gather_facts: no
  
  tasks:

    - name: Merge provided configuration with device configuration
      ios_l3_interfaces:
        config:
          - name: GigabitEthernet3/3
            ipv4:
            - address: 192.168.0.1/24
              secondary: True
