---
- name: asdf
  hosts: ios
  gather_facts: no
  
  tasks:

    - name: configure interface settings
      ios_config:
        authorize: yes
        lines:
          - description test interface
          - ip address 172.31.1.1 255.255.255.0
        parents: interface GigabitEthernet3/3
