---
- name: RUN COMMAND AND PRINT TO TERMINAL WINDOW
  hosts: ios
  gather_facts: false
  
  tasks:
    - name: configure interface settings
      ios_config:
        lines:
          - no switchport
          - description ios-config module
          - ip address 172.31.1.1 255.255.255.0
        parents: interface Gig1/2
