---
- name: RUN COMMAND AND PRINT TO TERMINAL WINDOW
  hosts: ios
  gather_facts: false
  
  tasks:
    - name: Merge provided configuration with device configuration
      ios_interfaces:
        config:
          - name: GigabitEthernet1/1
            description: 'Configured and Merged by Ansible Network'
            enabled: True
        state: merged
